### ISSUE TITLE
Cannot add Custom voice trained models

### ISSUE THREAD

**Issue by FemBoxbrawl** [tijo95/win_tts_piper#1]
It's really great! the TTS is super fast and realistic. i like it. but one problem i have is that i cannot add custom models. like, i can place them in the models folder, but it won't recognize them.

**Comment by FemBoxbrawl** [comment]
Turns out you have to format them in a specific way, for example "en-US-Name-High.onnx " so "lang-uage-Name-quality.onnx"

**Comment by tijo95** [comment]
hi yes I confirm ...
 Did you follow Piper's github for the model creation? He made available a google colab for super easy model creation.

https://www.youtube.com/watch?v=67QvWOp3dkU&t=697s

**Comment by tijo95** [comment]
piper can handle streaming too, but i don't have much time to develop it. and gradio i don't know, it slows me down a lot.

**Comment by FemBoxbrawl** [comment]
> hi yes I confirm ... Did you follow Piper's github for the model creation? He made available a google colab for super easy model creation.
> 
> https://www.youtube.com/watch?v=67QvWOp3dkU&t=697s

Yeah I got it to work, i just had to change the name and it worked! so all good.
