### ISSUE TITLE
outputs wav file not generated

### ISSUE THREAD

**Issue by franklin050187** [tijo95/win_tts_piper#12]
Hi, I did follow instructions on windows 11 but the wav file is not generated.

Example outputs : 
Llama.generate: prefix-match hit
Output generated in 1.72 seconds (29.73 tokens/s, 51 tokens, context 150, seed 1704263231)
tts: In English, that means "Hello, how are you?" In French, the response would be "Bonjour, je me sens bien, et toi?" Which translates to "Hello, I'm doing well, and you?" -> extensions\piper_tts\outputs\Assistant_1716471792.wav

extensions\piper_tts\outputs\ is empty

Any idea of why ?

This is a win11 N version with optionnal media pack installed

**Comment by tijo95** [comment]
Hi, you're lucky I was in my mailbox and saw your message lol.

In the model folder, the .onnx and .json files must be renamed the same way.

![68747470733a2f2f64726976652e676f6f676c652e636f6d2f75633f6578706f72743d766965772669643d31364a6b526d4f66434c2d45333758653656366a6d374d4a53685a7a4e48547972](https://github.com/tijo95/piper_tts/assets/144551901/c40dc49a-1901-45b5-9e1c-a276387d05cf)
