### ISSUE TITLE
This also works for linux with minimal modifications

### ISSUE THREAD

**Issue by Martin-Laclaustra** [tijo95/win_tts_piper#3]
This is the installation procedure (I suggest adding it to the readme), creating a link to piper executable, so that the python code in this extension can find it:
```
cd ###text-generation-webui dir###/extensions
git clone https://github.com/tijo95/win_tts_piper.git
cd win_tts_piper/
wget https://github.com/rhasspy/piper/releases/download/2023.11.14-2/piper_linux_x86_64.tar.gz
tar -xvf piper_linux_x86_64.tar.gz
rm piper_linux_x86_64.tar.gz 
cd piper; ln -r -s piper piper.exe
# download a model into model/
```
Alternatively, instead of creating a link, the extension code can be modified, and this also works:
```
cd ###text-generation-webui dir###/extensions
git clone https://github.com/tijo95/win_tts_piper.git
cd win_tts_piper/
wget https://github.com/rhasspy/piper/releases/download/2023.11.14-2/piper_linux_x86_64.tar.gz
tar -xvf piper_linux_x86_64.tar.gz
rm piper_linux_x86_64.tar.gz 
sed -i -e "s/^piper_path = Path('extensions\/win_tts_piper\/piper\/piper\.exe')/piper_path = Path('extensions\/win_tts_piper\/piper\/piper')/" script.py
# download a model into model/
```
... but in this case, updating the extension will break the installation.

**Comment by tijo95** [comment]
Hi, thanks for your work, don't hesitate to create a fork and port the improvements to the community, because I don't have the time to work on the extension right now.

**Comment by tijo95** [comment]
I'll give you access to the project

**Comment by FemBoxbrawl** [comment]
@Martin-Laclaustra , If you have the ability to create a piperTTS extension to silly Tavern (with a selectable voice per character, that would be awesome!

**Comment by tijo95** [comment]
@FemBoxbrawl,  I'm sorry I didn't get back to you sooner, but I'm running out of time.

**Comment by FemBoxbrawl** [comment]
@tijo95 no problem, all good

**Comment by tijo95** [comment]
@Martin-Laclaustra , I've given you access to the project, good luck.

**Comment by Martin-Laclaustra** [comment]
Thanks! That was a quick enrollment. I myself can not allocate also much time, but, at a minimum, I am going to add the information to the main page.
